language: go

go:
  - 1.3

install:
  - go get -t -v ./...
  - go install github.com/onsi/ginkgo/ginkgo

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - ginkgo -r -failOnPending -randomizeAllSpecs -race
