#!/bin/bash

set -e

export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/contraband/anderson
anderson

go install github.com/onsi/ginkgo/ginkgo
ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress "$@"
